before:
  hooks:
  - go mod download
builds:
- main: ./cmd/ctrsigcheck
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 5
  - 6
  - 7
archives:
- format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
